name: 'JSON Diff'
description: 'Diff 2 JSON string, and issue a PR comment'
inputs:
  string_a:
    description: 'Compare this'
    required: true
  string_b:  
    description: 'Against this'
    required: true
  github_token:
    description: "Github token, to get context"
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'